import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, Activity, CheckCircle2, ChevronLeft, ChevronRight } from "lucide-react";
import { FeatureContributors } from "./FeatureContributors";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

interface Prediction {
  patientId: number;
  prediction: string;
  confidence: number;
  topFeatures: Array<{ feature: string; importance: number }>;
}

interface PredictionResultsProps {
  predictions: Prediction[];
}

export const PredictionResults = ({ predictions }: PredictionResultsProps) => {
  const [expandedRow, setExpandedRow] = useState<number | null>(null);
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 20;
  const { toast } = useToast();

  const totalPages = Math.ceil(predictions.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentPredictions = predictions.slice(startIndex, endIndex);

  const downloadAllReports = () => {
    predictions.forEach((prediction) => {
      setTimeout(() => downloadReport(prediction), 100);
    });
    toast({
      title: "Downloading All Reports",
      description: `Generating ${predictions.length} patient reports. This may take a moment.`,
    });
  };

  const downloadReport = (prediction: Prediction) => {
    const report = `
RxCompass - Patient Diagnostic Report
=====================================

Patient ID: ${prediction.patientId}
Predicted Diagnosis: ${prediction.prediction}
Confidence Level: ${prediction.confidence.toFixed(2)}%
Generated: ${new Date().toLocaleString()}

TOP 10 FEATURE CONTRIBUTORS
---------------------------
${prediction.topFeatures
  .map((f, i) => `${i + 1}. ${f.feature}: ${f.importance.toFixed(2)}%`)
  .join("\n")}

---------------------------
This report is generated by RxCompass AI-powered diagnostic system.
Please consult with healthcare professionals for medical decisions.
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `patient_${prediction.patientId}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: `Patient ${prediction.patientId} report has been downloaded successfully.`,
    });
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-6 w-6 text-primary" />
                Prediction Results
              </CardTitle>
              <CardDescription>
                Analysis complete for {predictions.length} patient{predictions.length > 1 ? "s" : ""}
              </CardDescription>
            </div>
            <div className="flex items-center gap-3">
              <Badge variant="outline" className="bg-secondary text-secondary-foreground px-4 py-2">
                <CheckCircle2 className="h-4 w-4 mr-2" />
                {predictions.length} Processed
              </Badge>
              <Button
                onClick={downloadAllReports}
                variant="default"
                size="sm"
                className="bg-gradient-to-r from-primary to-accent hover:opacity-90"
              >
                <Download className="h-4 w-4 mr-2" />
                Download All Reports
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Patient ID</TableHead>
                <TableHead>Predicted Diagnosis</TableHead>
                <TableHead>Confidence</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {currentPredictions.map((pred) => (
                <>
                  <TableRow
                    key={pred.patientId}
                    className="cursor-pointer hover:bg-muted/50"
                    onClick={() => setExpandedRow(expandedRow === pred.patientId ? null : pred.patientId)}
                  >
                    <TableCell className="font-medium">#{pred.patientId}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className="bg-primary/10">
                        {pred.prediction}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <div className="w-24 h-2 bg-muted rounded-full overflow-hidden">
                          <div
                            className="h-full bg-gradient-to-r from-primary to-accent transition-all"
                            style={{ width: `${pred.confidence}%` }}
                          />
                        </div>
                        <span className="text-sm font-medium">{pred.confidence.toFixed(1)}%</span>
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={(e) => {
                          e.stopPropagation();
                          downloadReport(pred);
                        }}
                      >
                        <Download className="h-4 w-4 mr-2" />
                        Report
                      </Button>
                    </TableCell>
                  </TableRow>
                  {expandedRow === pred.patientId && (
                    <TableRow>
                      <TableCell colSpan={4} className="p-0">
                        <div className="p-4 bg-muted/30">
                          <FeatureContributors
                            contributors={pred.topFeatures}
                            patientId={pred.patientId}
                          />
                        </div>
                      </TableCell>
                    </TableRow>
                  )}
                </>
              ))}
            </TableBody>
          </Table>
          
          {/* Pagination Controls */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between pt-6 border-t">
              <p className="text-sm text-muted-foreground">
                Showing {startIndex + 1} to {Math.min(endIndex, predictions.length)} of {predictions.length} patients
              </p>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                >
                  <ChevronLeft className="h-4 w-4 mr-1" />
                  Previous
                </Button>
                <div className="flex items-center gap-1">
                  {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                    let pageNum;
                    if (totalPages <= 5) {
                      pageNum = i + 1;
                    } else if (currentPage <= 3) {
                      pageNum = i + 1;
                    } else if (currentPage >= totalPages - 2) {
                      pageNum = totalPages - 4 + i;
                    } else {
                      pageNum = currentPage - 2 + i;
                    }
                    return (
                      <Button
                        key={pageNum}
                        variant={currentPage === pageNum ? "default" : "outline"}
                        size="sm"
                        onClick={() => setCurrentPage(pageNum)}
                        className="w-10"
                      >
                        {pageNum}
                      </Button>
                    );
                  })}
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                  disabled={currentPage === totalPages}
                >
                  Next
                  <ChevronRight className="h-4 w-4 ml-1" />
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
